plugins:
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

Layout/LineLength:
  Max: 120

RSpec/NestedGroups:
  Max: 5

RSpec/VerifiedDoubles:
  Enabled: false
